version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm_service
    restart: unless-stopped
    ports:
      - "8010:8000"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE__TOKEN}
      - HF_HOME=/models
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - type: bind
        source: ${HOME}/.cache/huggingface
        target: /models
    command:
      - --model
      - anhalu/qwen-baseline-time-function-calling-v3
      - --port
      - "8000"
      - --host
      - 0.0.0.0
    gpus: all
    networks:
      - app-tier
    env_file:
      - .env

  query:
    build:
      context: .
      dockerfile: cores/Dockerfile
    container_name: query_service
    restart: unless-stopped
    ports:
      - "8020:8020"
    environment:
      - BASELINE__BASE_URL=${BASELINE__BASE_URL}
      - BASELINE__PORT=${BASELINE__PORT}
      - BASELINE__API_KEY=${BASELINE__API_KEY}
      - BASELINE__MODEL_NAME=${BASELINE__MODEL_NAME}
      - TIME__BASE_URL=${TIME__BASE_URL}
      - TIME__PORT=${TIME__PORT}
      - TIME__API_KEY=${TIME__API_KEY}
      - TIME__MODEL_NAME=${TIME__MODEL_NAME}
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8020"]
    networks:
      - app-tier
    env_file:
      - .env